# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1395695035);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1395695155);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1395735893);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1395716515);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.lastDir", "/home/furch/Downloads");
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 14);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.defaultenginename", "Wikipedia (en)");
user_pref("browser.search.selectedEngine", "Wikipedia (en)");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140214013806");
user_pref("browser.slowStartup.averageTime", 707);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage", "https://www.google.com/");
user_pref("browser.startup.homepage_override.buildID", "20140214013806");
user_pref("browser.startup.homepage_override.mstone", "27.0.1");
user_pref("browser.syncPromoViewsLeftMap", "{\"addons\":4,\"bookmarks\":0}");
user_pref("datareporting.healthreport.lastDataSubmissionFailureTime", "1395728237346");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1395728236817");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1395814637346");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAccepted", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1395694857624");
user_pref("datareporting.policy.dataSubmissionPolicyResponseTime", "1395723690768");
user_pref("datareporting.policy.dataSubmissionPolicyResponseType", "accepted-implicit-time-elapsed");
user_pref("datareporting.policy.firstRunTime", "1393239344526");
user_pref("datareporting.sessions.current.activeTicks", 3);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 579);
user_pref("datareporting.sessions.current.main", 54);
user_pref("datareporting.sessions.current.sessionRestored", 679);
user_pref("datareporting.sessions.current.startTime", "1395780817120");
user_pref("datareporting.sessions.current.totalTime", 12);
user_pref("datareporting.sessions.currentIndex", 14);
user_pref("datareporting.sessions.previous.10", "{\"s\":1395735773124,\"a\":81,\"t\":403,\"c\":true,\"m\":54,\"fp\":841,\"sr\":920}");
user_pref("datareporting.sessions.previous.11", "{\"s\":1395736179896,\"a\":3,\"t\":13,\"c\":true,\"m\":64,\"fp\":831,\"sr\":916}");
user_pref("datareporting.sessions.previous.12", "{\"s\":1395736781458,\"a\":21,\"t\":109,\"c\":true,\"m\":65,\"fp\":611,\"sr\":717}");
user_pref("datareporting.sessions.previous.13", "{\"s\":1395737512378,\"a\":2,\"t\":9,\"c\":true,\"m\":64,\"fp\":557,\"sr\":660}");
user_pref("datareporting.sessions.previous.9", "{\"s\":1395694794412,\"a\":16,\"t\":39348,\"c\":true,\"m\":134,\"fp\":852,\"sr\":931}");
user_pref("datareporting.sessions.prunedIndex", 8);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 15);
user_pref("extensions.enabledAddons", "%7Be5bbc237-c99b-4ced-a061-0be27703295f%7D:1.3,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:27.0.1");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20140319.01");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1393722495000,\"rdfTime\":1392335782000}}},{\"name\":\"app-profile\",\"addons\":{\"{e5bbc237-c99b-4ced-a061-0be27703295f}\":{\"descriptor\":\"/home/furch/.mozilla/firefox/so2o2s1c.default/extensions/{e5bbc237-c99b-4ced-a061-0be27703295f}.xpi\",\"mtime\":1395735773000}}}]");
user_pref("extensions.lastAppVersion", "27.0.1");
user_pref("extensions.lastPlatformVersion", "27.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("gecko.buildID", "20140214013806");
user_pref("gecko.mstone", "27.0.1");
user_pref("general.autoScroll", true);
user_pref("idle.lastDailyNotification", 1395697045);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1395723692);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("privacy.cpd.offlineApps", true);
user_pref("privacy.cpd.siteSettings", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1395697045);
user_pref("toolkit.startup.last_success", 1395780817);
user_pref("toolkit.telemetry.previousBuildID", "20140214013806");
user_pref("urlclassifier.download_allow_table", "");
user_pref("urlclassifier.download_block_table", "");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1398329519);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
